[package]
name = "db"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
log.workspace = true
serde.workspace = true
surrealdb.workspace = true
teloxide.workspace = true
