[package]
name = "db"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
bon.workspace = true
i18n.workspace = true
log.workspace = true
sqlx.workspace = true
teloxide.workspace = true

common.workspace = true

[dev-dependencies]
tokio.workspace = true
