[package]
name = "db"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
i18n.workspace = true
log.workspace = true
sqlx.workspace = true
teloxide.workspace = true
